using System.IO;
using System.Text;
using NUnit.Framework;

namespace ButterflyNet.Parser.Tests {
	[TestFixture]
	public class FormattingHelpGenerator {

		[Test]
		public void Generate_html_formatting_help_file() {
			const string helpMarkup = @"
! Butterfly Markup
(-''auto-generated on __[::timestamp]__''-)

__Butterfly__ is a semantic markup syntax created and developed by [http://tommymontgomery.com/|Tommy Montgomery]. 
It is similar to many wiki syntaxes (such as [http://www.mediawiki.org/wiki/MediaWiki|MediaWiki]). It's goal is to 
be familiar, easy to read, and simple to use.

This document serves as both a test of the markup itself and documentation on how to use it. This document was 
automatically generated by a unit test using __Butterfly__ itself to generate everything inside the ==<body>== tag.

!! Output Formats
__Butterfly__ uses an ''Analyzer'' to transform markup to an output format. The default is HTML, but you can implement 
your own analyzer by injecting a custom implementation of ==ButterflyNet.Parser.ButterflyAnalyzer== into a 
==ButterflyNet.Parser.ButterflyParser== instance.

!! Text Formatting
|! Style|! Example|! Result|
| Bold| ==[!this text is __bold__]==| this text is __bold__|
| Emphasis| ==[!this text is ''emphasized'']==| this text is ''emphasized''|
| Teletype| ==[!this text is ==reminiscient of a typewriter==]==| this text is ==reminiscient of a typewriter==|
| Underline| ==[!this text is --important--]==| this text is --important--|
| Strike-through| ==[!this text is ---deleted---]==| this text is ---deleted---|
| Big| ==[!this text is (+big and (+huge+)+)]==| this text is (+big and (+huge+)+)|
| Small| ==[!this text is (-small and (-tiny-)-)]==| this text is (-small and (-tiny-)-)|

!! Lists
!!! Bullet Lists

Bulleted lists are opened by a ==*== (unordered) or a ==#== (ordered) at the start of a line. To increase the nesting 
level, add more asterisks or hashes. You cannot mix list types at the same depth.

The following markup:
{{{{
* Countries
*# United States
*#* West Coast
*#** Washington
*#** Oregon
*#** California
*#* East Coast
*#** Florida
*#** Maryland
*#** Georgia
*#** Massachusetts
*# Canada
*# Mexico
* See also
** Wikipedia: [http://en.wikipedia.org/wiki/List_of_sovereign_states]
}}}}


Gets transformed into:

* Countries
*# United States
*#* West Coast
*#** Washington
*#** Oregon
*#** California
*#* East Coast
*#** Florida
*#** Maryland
*#** Georgia
*#** Massachusetts
*# Canada
*# Mexico
* See also
** Wikipedia: [http://en.wikipedia.org/wiki/List_of_sovereign_states]

";

			var fileContext = string.Format(@"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Strict//EN""
""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"">

<html xmlns=""http://www.w3.org/1999/xhtml"" lang=""en-US"">
	<head>
		<title>Butterfly Formatting Help</title>
		<meta http-equiv=""content-type"" content=""text/html; charset=utf-8""/>
		<style type=""text/css"">
			body {{
				background-color: #FFFFFF;
				color: #000000;
				font-family: ""Droid Sans"", Verdana, sans-serif;
				font-size: 12pt;
				width: 80%;
				min-width: 800px;
				margin: auto;
			}}
			
			code, tt, pre {{
				font-family: Consolas, Inconsolata, ""Courier New"", monospace;
			}}
			
			dt {{
				background-color: #EEEEEE;
				font-weight: bold;
				margin-top: 10px;
			}}
			
			a {{
				color: #000099;
				text-decoration: underline;
			}}
			a:hover {{
				background-color: #EEEEEE;
			}}

			table {{
				border-collapse: collapse;
			}}
			table, td, th {{
				border: 1px solid #999999;
				padding: 5px;
			}}
			th {{
				background-color: #CBB1CA;
			}}
		</style>
	</head>
	<body>
{0}
	</body>
</html>", new ButterflyParser().LoadDefaultStrategies().ParseAndReturn(helpMarkup));

			File.WriteAllText(@"..\..\formatting.html", fileContext, Encoding.UTF8);
		}

	}
}