var ScopeTypeCache = {
	strong: "strong",
	emphasis: "emphasis",
	underline: "underline",
	strikeThrough: "strikeThrough",
	teletype: "teletype",
	small: "small",
	big: "big",
	unparsed: "unparsed",
	unescaped: "unescaped",
	link: "link",
	module: "module",
	macro: "macro",
	lineBreak: "lineBreak",
	
	horizontalRuler: "horizontalRuler",
	paragraph: "paragraph",
	blockquote: "blockquote",
	orderedList: "orderedList",
	unorderedList: "unorderedList",
	listItem: "listItem",
	preformatted: "preformatted",
	preformattedLine: "preformattedLine",
	table: "table",
	tableRow: "tableRow",
	tableRowLine: "tableRowLine",
	tableHeader: "tableHeader",
	tableCell: "tableCell",
	definitionList: "definitionList",
	definitionTerm: "definitionTerm",
	definition: "definition",
	multiLineDefinition: "multiLineDefinition",
	header: "header"
};